### ISSUE TITLE
`DCL51`:  use-of-single-underscore-reserved-prefix hits when using lambda functions.

### ISSUE THREAD

**Issue by MFaisalZaki** [github/codeql-coding-standards#57] opened 2022-08-17 09:16 UTC
### Affected rules
 - cpp/cert/use-of-single-underscore-reserved-prefix

### Description
The rule generates an alert on normal lambda functions. 
Message: " Name _FUN uses the reserved prefix  "

### Example
```
#include <iostream>
#include <string>

int main() {

    auto is_digit = [](std::string& word) {
			std::string::const_iterator it = word.begin();
			while (it != word.end() && std::isdigit(*it)) ++it;
			return !word.empty() && it == word.end();
		};

    std::string my_word("10");
    auto test_word = is_digit(my_word);

    return 0;
}
```

**Comment by lcartey** [comment] 2022-08-17 21:00
Thanks for reporting this!

This is caused by a leaky abstraction in how lambdas are represented by our compiler frontend and within our database schema. `_FUN` is a compiler generated function which contains the body of the lambda expression. We should exclude it as generated, but we currently don't. We will add this to our backlog.

**Comment by rvermeulen** [comment] 2024-01-10 23:29
Fixed in https://github.com/github/codeql-coding-standards/pull/301.

**Closed by rvermeulen** 2024-01-10 23:29 UTC
Labels: Difficulty-Low, Impact-Medium, false positive/false negative
